### ISSUE TITLE
Could not open bplist file with libfplist_property_list_copy_from_byte_stream?

### ISSUE THREAD

**Issue by DK1998U** [libyal/libfplist#1]
it can parse test/data/property-list.1 test/data/property-list.1 but when i try to parse test/binary-property_list.3 i got an error

libfplist_property_list_copy_from_byte_stream:unable to parse XML

**Comment by DK1998U** [comment]
it can parse test/data/property-list.1 test/data/property-list.2 but when i try to parse test/binary-property_list.3 i got an error

libfplist_property_list_copy_from_byte_stream:unable to parse XML

**Comment by joachimmetz** [comment]
(removed duplicate post)

Where do you see `test/data/property-list.1`, `test/data/property-list.2`, `test/binary-property_list.3`?

Or do you mean `tests/data/binary_property_list.1` ?

Per README the library is experimental. It is mainly intended to be used by other libyal projects. Binary (or other) plist files are not yet supported.

**Comment by joachimmetz** [comment]
Changed the README to be more explicit about which plist formats are currently supported
https://github.com/libyal/libfplist/commit/1a250824dbddd9710231fd1c07c36187ea2fcbe7

**Comment by joachimmetz** [comment]
Closing issue, reopen if this was not the question you were asking
